name: Convert SIGMA to CrowdStrike Queries

on:
  push:
    paths:
      - "sigma-rules/**"  # `sigma-rules/`フォルダの変更がトリガー
  workflow_dispatch:  # 手動実行も許可

jobs:
  convert-sigma:
    runs-on: ubuntu-latest

    steps:
    # リポジトリをクローン
    - name: Checkout repository
      uses: actions/checkout@v3

    # Python環境のセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 必要なツールのセットアップ
    - name: Install dependencies and sigma-cli
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install sigma-cli
        sigma plugin install crowdstrike
        chmod 777 fql-rules
        
    - name: Convert SIGMA to FQL
      run: |
        for file in sigma-rules/*.yml; do
           echo "Converting $file..."
           output=$(sigma convert -t log_scale -p crowdstrike_falcon "$file")
           echo "$output"
           echo "$output" > "fql-rules/$(basename "$file" .yml).fql"
        done
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add fql-rules/
        git commit -m "Update fql-rules with new fql files" || echo "No changes to commit"
        git push
